/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.myproject1;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author Nina
 */
public class UserCardLayoutPanel extends javax.swing.JPanel {

    //private static final Color UNSELECTED = Color.BLACK;
    private static final Color SELECTED = Color.LIGHT_GRAY;

    private static final String PNL_MOVIES = "pnlMovies";
    
    private CardLayout layout;
    
    /**
     * Creates new form UserCardLayoutPanel
     */
    public UserCardLayoutPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        lblMovies = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        pnlMovies = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        lblMenu.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(51, 51, 0));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");

        lblMovies.setBackground(new java.awt.Color(204, 204, 255));
        lblMovies.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lblMovies.setForeground(new java.awt.Color(0, 0, 0));
        lblMovies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovies.setText("Movies");
        lblMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMoviesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(lblMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        pnlCards.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlMoviesLayout = new javax.swing.GroupLayout(pnlMovies);
        pnlMovies.setLayout(pnlMoviesLayout);
        pnlMoviesLayout.setHorizontalGroup(
            pnlMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        pnlMoviesLayout.setVerticalGroup(
            pnlMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        pnlCards.add(pnlMovies, "pnlMovies");

        jSplitPane1.setRightComponent(pnlCards);

        add(jSplitPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lblMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoviesMouseClicked
        layout.show(pnlCards, PNL_MOVIES);
        lblMovies.setForeground(SELECTED);
    }//GEN-LAST:event_lblMoviesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMovies;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlMovies;
    // End of variables declaration//GEN-END:variables

    private void init() {
        initMoviesPanel();
    }

    private void initMoviesPanel() {
        layout= (CardLayout) pnlCards.getLayout();
        lblMovies.setForeground(SELECTED);
        
        pnlMovies.setLayout(new BorderLayout());
        pnlMovies.add(new MoviesPanel());
    }
}
